name: Deploy Backend

on:
push:
branches:
- main

env:
FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
deploy:
runs-on: ubuntu-latest


steps:
  - name: Checkout repository
    uses: actions/checkout@v5

  - name: Setup Node.js
    uses: actions/setup-node@v5
    with:
      node-version: 22

  - name: Configure SSH
    run: |
      mkdir -p ~/.ssh

      printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      chmod 600 ~/.ssh/id_rsa

      ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

  - name: Test SSH Connection
    run: |
      ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "echo SSH SUCCESS"

  - name: Deploy Backend
    run: |
      ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

        set -e

        echo "Connected to server"

        cd ${{ secrets.APP_PATH }}

        echo "Fetching latest code..."
        git fetch origin

        git reset --hard origin/main

        echo "Installing dependencies..."
        npm install

        echo "Restarting PM2 process..."

        if pm2 describe "${{ secrets.PM2_PROCESS_NAME }}" > /dev/null
        then
          pm2 restart "${{ secrets.PM2_PROCESS_NAME }}"
        else
          pm2 start server.js --name "${{ secrets.PM2_PROCESS_NAME }}"
        fi

        pm2 save

        echo "Deployment completed successfully"

      EOF
```
